export { default as Main } from './main.tsx'
export { default as Service } from './service.tsx'
export { default as Blog } from './blog.tsx'
export { default as BlogDetail } from './blogDetail.tsx'
export { default as Reviews } from './reviews.tsx'
export { default as Calculator } from './calculator.tsx'