export { default as AdminPage } from './Admin.tsx'
export { default as AddClient } from './AddClient.tsx'
export { default as Clients } from './Clients.tsx'
export { default as AddShippers } from './AddShipers.tsx'
export { default as Shippers } from './Shipers.tsx'
export { default as AddConsignessComp } from './AddConsignees.tsx'
export { default as Conignees } from './Conigness.tsx'
export { default as AddDispatch} from './AddDispatch.tsx'
export { default as Dispatch} from './Dispatch.tsx'
export { default as Message} from './Message.tsx'
export { default as Chat} from './Chat.tsx'
export { default as Wallet} from './Wallet.tsx'
export { default as Rates} from './Rates.tsx'
export { default as Way} from './Way.tsx'
export { default as AdminLogin} from './AdminLogin.tsx'
export { default as AdminService} from './AddServices.tsx'